#!/bin/sh

# Merge in defaults and keymaps
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
[ -f $sysresources ] && xrdb -merge "$sysresources"
[ -f $sysmodmap ] && xmodmap "$sysmodmap"
[ -f $userresources ] && xrdb -merge "$userresources"
[ -f $usermodmap ] && xmodmap "$usermodmap"

# Set X-specific environment
[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

if $(xrandr | grep -q '^HDMI1 connected'); then
	xrandr --output HDMI1 --auto --output LVDS1 --off
fi

# XBK Settings
setxkbmap de adnw

fcitx &
feh --bg-fill ${XDG_CONFIG_HOME:-$HOME/.config}/wallpaper &
start-pulseaudio-x11 &
compton &
exec ${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/scripts/wm
