#!/bin/sh

#export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/dbus/user_bus_socket"

# Not set in /etc/profile.d anymore
export _JAVA_AWT_WM_NONREPARENTING=1

# Set Infinality style
export USE_STYLE="3"

# Need this in order to use GTK style for Qt
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Use fcitx as input method framework
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

export TERMINAL=termite
