#! /bin/sh

i=1
for monitor in $(bspc query -M); do
	bspc monitor $monitor -n "$i" -d i ii iii iv v vi
	let i++
done
unset i

bspc config border_width 4
bspc config window_gap 12
bspc config split_ratio 0.52
# No borders/gaps in monocle mode
bspc config borderless_monocle true
bspc config gapless_monocle true
# Make presel toggleable
bspc config auto_alternate true
bspc config auto_cancel true
# Focus follows pointer
bspc config focus_follows_pointer true
