#!/bin/sh

export PAGER=less EDITOR=nvim BROWSER=firefox
# Smart case searching as in Vim
export LESS="-Ri"

# XDG basedir specification
[ -z $XDG_CONFIG_HOME ] && export XDG_CONFIG_HOME="$HOME/.config"
[ -z $XDG_DATA_HOME ] && export XDG_DATA_HOME="$HOME/.local/share"
[ -z $XDG_CACHE_HOME ] && export XDG_CACHE_HOME="$HOME/.cache"
if [ -z $XDG_DATA_DIRS ]; then
    export XDG_DATA_DIRS="/usr/local/share:/usr/share"
else
    export XDG_DATA_DIRS="/usr/local/share:/usr/share:$XDG_DATA_DIRS"
fi
if [ -z $XDG_CONFIG_DIRS ]; then
    export XDG_CONFIG_DIRS="/etc/xdg"
else
    export XDG_CONFIG_DIRS="/etc/xdg:$XDG_CONFIG_DIRS"
fi

export VIMPERATOR_INIT=":source $XDG_CONFIG_HOME/vimperator/vimperatorrc"
# Make Java applications look less ugly:
# - Use system font settings
# - Use native GTK look and feel
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
