#!/bin/sh

# Merge in defaults and keymaps
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
[ -f $sysresources ] && xrdb -merge "$sysresources"
[ -f $sysmodmap ] && xmodmap "$sysmodmap"
[ -f $userresources ] && xrdb -merge "$userresources"
[ -f $usermodmap ] && xmodmap "$usermodmap"

# Set X-specific environment
[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

!!@@
fcitx &

# XBK Settings
XKBDIR="${XDG_CONFIG_HOME:-$HOME/.config}/xkb"
XKBKEYMAPFILE="$XKBDIR/keymaps/default.xkb"
xkbcomp -I"$XKBDIR" "$XKBKEYMAPFILE" "$DISPLAY"

# Holy god yes xcape
# Has left Control key act as Escape if it's not used as a modifier Now,
# remember: Capslock is my control key, so this basically supercharges my left
# pinkie
xcape -e 'Control_L=Escape'
feh --bg-fill ${XDG_CONFIG_HOME:-$HOME/.config}/wallpaper &
start-pulseaudio-x11 &
compton &
exec ${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/scripts/wm
