#!/bin/sh

# Merge in defaults and keymaps
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
[ -f $sysresources ] && xrdb -merge "$sysresources"
[ -f $sysmodmap ] && xmodmap "$sysmodmap"
[ -f $userresources ] && xrdb -merge "$userresources"
[ -f $usermodmap ] && xmodmap "$usermodmap"

# Set X-specific environment
[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

start-pulseaudio-x11 &
compton --backend glx &
exec i3
