#!/bin/sh

#export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/dbus/user_bus_socket"

# Not set in /etc/profile.d anymore
export _JAVA_AWT_WM_NONREPARENTING=1

# Need this in order to use GTK style for Qt
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Use fcitx as input method framework
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# XBK Settings
XKBDIR="${XDG_CONFIG_HOME:-$HOME/.config}/xkb"
XKBKEYMAPFILE="$XKBDIR/keymaps/default.xkb"
xkbcomp -I"$XKBDIR" "$XKBKEYMAPFILE" "$DISPLAY"

export TERMINAL=termite

# Holy god yes xcape
# Has left Control key act as Escape if it's not used as a modifier Now,
# remember: Capslock is my control key, so this basically supercharges my left
# pinkie
xcape -e 'Control_L=Escape'
